--- #YAML:1.0
name:                Bio-LITE-Taxonomy
version:             0.04
abstract:            Lightweight and efficient taxonomic tree manager
license:             perl
author:              
    - Miguel Pignatelli <emepyc@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.87
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
